config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#welcome"
   resources :genres
   resources :directors
   resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :genre
  belongs_to :director
  enum is_available: { 'Em breve': 1, 'Nos cinemas': 2 }
  has_one_attached :poster
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def new
  end
  def index
    @directors = Director.all
  end
  def show
    @director = Director.find(params[:id])
    @movies = Movie.where(director_id: params[:id])
  end

  def create
    @director = Director.new(name: params[:director][:name], nationality: params[:director][:nationality], date: params[:director][:date], genre_id: params[:director][:genre])
    @director.save 
    redirect_to root_path
  end

  def edit
    @director = Director.find(params[:id])
  end

  def update
    @director = Director.find(params[:id])
    @director.update(params.require(:director).permit(:name, :nationality, :date, :genre_id))
    redirect_to root_path
  end

  def destroy
    director = Director.find(params[:id])
    director.destroy 
    redirect_to root_path
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def new
  end
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
    @movies = Movie.where(genre_id: params[:id])
  end

  def create
    @genre = Genre.new(name: params[:genre][:name])
    @genre.save
    redirect_to root_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(params.require(:genre).permit(:description, :status))
    redirect_to root_path
  end
  def destroy
    genre = Genre.find(params[:id]) 
    genre.destroy 
    redirect_to root_path
  end

  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def welcome
        @genres = Genre.all
        @directors = Director.all
        @movies = Movie.all
    end
  
    
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def new
  end

  def index 
      @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(title: params[:movie][:title], year: params[:movie][:year], plot: params[:movie][:plot], country: params[:movie][:country], running_time: params[:movie][:running_time], poster: params[:movie][:poster], genre_id: params[:movie][:genre], director_id: params[:movie][:director])
    p params
    @movie.save
    redirect_to root_path
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(params.require(:movie).permit(:title, :year, :plor, :country, :running_time, :is_available, :poster, :director_id, :genre_id))
    redirect_to root_path
  end

  def destroy
    movie = Movie.find(params[:id])
    movie.destroy
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directors/edit.html.erb
<%= form_for @director do |f| %>
  <div class="col-lg-4 m-4">
  <%= f.label :name, 'Nome', class:"form-label" %>
  <%= f.text_field :name, class:"form-control" %>
  <%= f.label :nationality, 'Nacionalidade', class:"form-label" %>
  <%= f.text_field :nationality, class:"form-control" %>
  <%= f.label :date, 'Nascimento', class:"form-label" %>
  <%= f.text_field :date, class:"form-control" %>
  <%= f.label :genre, 'Gênero preferido', class:"form-label" %>
  <%=f.collection_select :genre, Genre.all, :id, :name, class:"form-control" %> <br>
  <%= f.submit 'Editar', class:"w-30 btn btn-primary mt-4" %>
  </div>
<% end %>
<%= button_to "Destroy this classroom" , @director,
	method: :delete,method: :delete, class:"w-30 btn btn-danger ms-4"  %>

app/views/directors/index.html.erb
<h1>Diretores:</h1>

<% @directors.each do |director| %>
    <%= director.name %>  <%= link_to '+', director_path(director.id) %><br />

<% end %>

app/views/directors/new.html.erb
  <%= form_for Director.new do |f| %>
  <div class="col-lg-4 m-4">
    <div>
      <%= f.label :name, 'Nome', class:"form-label" %>
    </div>
    <div>
      <%= f.text_field :name, class:"form-control" %>
    </div>
    <div>
      <%= f.label :nationality, 'Nacionalidade' %>
    </div>
    <div>
      <%= f.text_field :nationality, class:"form-control" %>
    </div>
    <div>
      <%= f.label :date, 'Nascimento', class:"form-label" %>
    </div>
    <div>
      <%= f.text_field :date, class:"form-control" %>
    </div>
    <div>
      <%= f.label :genre, 'Gênero preferido', class:"form-label" %>
    </div>
    <div>
      <%=f.collection_select :genre, Genre.all, :id, :name, class:"form-control" %>
    </div>
      
    <%= f.submit 'Editar', class:"w-30 btn btn-primary mt-4" %>
  
    <%= f.submit 'Criar', class:"w-30 btn btn-primary mt-4" %>
  </div>
<% end %>

app/views/directors/show.html.erb
<h1>Diretor: <%= @director.name%> </h1>
<% if flash[:notice] %>
  <div style="margin: 10px 0px">
    <%= flash[:notice] %>
  </div>
  <% end %>
<dl>
<dt><strong>Nome: </strong><%= @director.name %></dt>
<dt><strong>Nacionalidade: </strong><%= @director.nationality %></dt>
<dt><strong>Data: </strong><%= @director.date %></dt>
<dt><strong>Genero Preferido: </strong><%= @director.genre.name%></dt>

<%= link_to 'Editar', edit_director_path %>
</dl>
<h3>Filmes de <%= @director.name %> </h3>
<% @movies.each do |movie| %>
<%= movie.title %> <br />
<% end %>

app/views/genres/edit.html.erb
<%= form_for @genre do |f| %>
  <div class="col-lg-4 m-4">
    <div>
      <%= f.label :name, 'Nome', class:"form-label" %>
      <%= f.text_field :name, class:"form-control" %>
    </div>
  <%= f.submit 'Editar', class:"w-30 btn btn-primary mt-4" %>
  </div>
<% end %>
<%= button_to "Destroy this classroom" , @task,
	method: :delete,method: :delete, class:"w-30 btn btn-danger ms-4" %>

  

app/views/genres/index.html.erb
<h1>Generos:</h1>

<% @genres.each do |genre| %>
    <%= genre.name %>  <%= link_to '+', genre_path(genre.id) %><br />

<% end %>

app/views/genres/new.html.erb
<%= form_for Genre.new do |f| %>
<div class="col-lg-4 m-4">
  <div>
    <%= f.label :name, 'Nome', class:"form-label" %>
    <%= f.text_field :name, class:"form-control" %>
  </div>

  <%= f.submit 'Criar', class:"w-30 btn btn-primary mt-4" %>
  </div>
<% end %>

app/views/genres/show.html.erb
<h1>Gênero: <%= @genre.name%> </h1>
<% if flash[:notice] %>
  <div style="margin: 10px 0px">
    <%= flash[:notice] %>
  </div>
  <% end %>
<dl>
<dt><strong>Nome: </strong><%= @genre.name %></dt>
<%= link_to 'Editar', edit_genre_path %>
<br />
<h3><Filmes de <%= @genre.name%> /h3>
<% @movies.each do |movie| %>
<%= movie.title %> <br />
<% end %>
</dl>

app/views/home/welcome.html.erb
<div class="p-5 text-center bg-body-tertiary rounded-3">
   
    <h1 class="text-body-emphasis">Cadastro de Filmes</h1>
    <p class="col-lg-8 mx-auto fs-5 text-muted">
      <h3>Filmes</h3>

     
  <%= link_to 'Cadastrar', new_movie_path %> - 
  
  <%= link_to 'Ver todos', movies_path %>
 
<h3>Generos:</h3>

  <%= link_to 'Cadastrar', new_genre_path %> - 

  <%= link_to 'Ver todos', genres_path %>

<h3>Diretores:</h3>

  <%= link_to 'Cadastrar', new_director_path %>  - 
 
  <%= link_to 'Ver todos', directors_path %>

</p>
    
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container my-5">
      <%= yield%>
    </div>
    
  </body>
</html>

app/views/movies/edit.html.erb
<%= form_for @movie do |f| %>
 <div class="col-lg-4 m-4">
    <div>
      <%= f.label :title, 'Título', class:"form-label" %>
      <%= f.text_field :title, class:"form-control"%>
    </div>
    <div>
       <%= f.label :year, 'Ano de lançamento', class:"form-label" %>
      <%= f.text_field :year, class:"form-control" %>
    </div>
    <div>
   <%= f.label :country, 'País de origem', class:"form-label" %>
      <%= f.text_field :country, class:"form-control" %>
    </div>
    <div>
    <%= f.label :plor, 'Sinopse', class:"form-label" %>
      <%= f.text_field :plot, class:"form-control" %>
    </div>
    <div>
      <%= f.label :genre, 'Gênero', class:"form-label" %>
      <%=f.collection_select :genre, Genre.all, :id, :name, class:"form-control"  %>
    </div>
    <div>
      <%= f.label :director, 'Diretor', class:"form-label" %>
      <%=f.collection_select :director, Director.all, :id, :name, class:"form-control"  %>
    </div>
    <div>
      <div>
      <%= f.label :is_available, 'Disponível', class:"form-label" %>
       <%= f.select :is_available, options_for_select(Movie.is_availables.map {|key, value| [key.titleize, Movie.is_availables.key(value)]}, @movie.is_available) %>
    </div>
      <%= f.label :is_available, 'Poster', class:"form-label" %>
      <%= f.file_field :poster, class:"form-control" %>
    </div>
    <%= f.submit 'Editar', class:"w-30 btn btn-primary mt-4" %> 
<% end %>
<%= button_to "Destroy this classroom" , @movie, method: :delete,method: :delete, class:"w-30 btn btn-danger mt-4" %>

app/views/movies/index.html.erb
<h1>Filmes:</h1>
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
  
<% @movies.each do |movie| %>
  <div class="col">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-2">
            <h4 class="my-0 fw-normal"><%= movie.title %> </h4>
        </div>
        <div class="card-body">
            <% if movie.poster.representable? %>
                <%= image_tag(movie.poster, style:"width:150px") %>
            <% else %>
                <p>Sem poster cadastrado</p>
            <% end %>
            <br />
            <br />
            <strong>Disponibilidade: </strong><%= movie.is_available %> <br />
            <strong>Ano de lançamento: </strong><%= movie.year %>  <br />
            <%= link_to 'Ver mais info', movie_path(movie.id) %><br />
        
        </div>
        </div>
    </div>
  
<% end %>   
    
</div>

app/views/movies/new.html.erb
  <%= form_for Movie.new do |f| %>
  <div class="col-lg-4 m-4">
    <div>
      <%= f.label :title, 'Título', class:"form-label" %>
      <%= f.text_field :title, class:"form-control"%>
    </div>
    <div>
       <%= f.label :year, 'Ano de lançamento', class:"form-label" %>
      <%= f.text_field :year, class:"form-control" %>
    </div>
    <div>
   <%= f.label :country, 'País de origem', class:"form-label" %>
      <%= f.text_field :country, class:"form-control" %>
    </div>
    <div>
    <%= f.label :plor, 'Sinopse', class:"form-label" %>
      <%= f.text_field :plot, class:"form-control" %>
    </div>
    <div>
      <%= f.label :genre, 'Gênero', class:"form-label" %>
      <%=f.collection_select :genre, Genre.all, :id, :name, class:"form-control"  %>
    </div>
    <div>
      <%= f.label :director, 'Diretor', class:"form-label" %>
      <%=f.collection_select :director, Director.all, :id, :name, class:"form-control"  %>
    </div>
     <div>
      <%= f.label :is_available, 'Disponível', class:"form-label" %>
       <%= f.select :is_available, options_for_select(Movie.is_availables.map {|key, value| [key.titleize, Movie.is_availables.key(value)]}, @movie.is_available) %>
    </div>
    <div>
      <%= f.label :is_available, 'Disponível', class:"form-label" %>
      <%= f.file_field :poster, class:"form-control" %>
    </div>
   
      <%= f.submit 'Editar', class:"w-30 btn btn-primary mt-4" %>
      
      <%= f.submit 'Criar', class:"w-30 btn btn-primary mt-4" %>
      </div>
<% end %>

app/views/movies/show.html.erb
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
  

  <div class="col">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-2">
            <h4 class="my-0 fw-normal"><%= @movie.title %> </h4>
        </div>
        <div class="card-body">
            <% if @movie.poster.representable? %>
                <%= image_tag(@movie.poster, style:"width:150px") %>
            <% else %>
                <p>Sem poster cadastrado</p>
            <% end %>
            <br />
            <br />
            <strong>Diretor: </strong><%= @movie.director.name %> <br />
            <strong>Disponibilidade: </strong><%= @movie.is_available %> <br />
            <strong>Ano de lançamento: </strong><%= @movie.year %>  <br />
            <%= link_to 'Editar', edit_movie_path(@movie.id) %><br />
        
        </div>
        </div>
    </div>
  
    
</div>